### ISSUE TITLE
Submission fails with "ERROR: null".

### ISSUE THREAD

**Issue by nisegami** [thomas4g/git-submitter#14]
Github usernames match. See attached log. 

[git-submitter0.txt](https://github.com/thomas4g/git-submitter/files/145123/git-submitter0.txt)

**Comment by thomas4g** [comment]
Are you on Windows?

**Comment by kjcartledge** [comment]
Confirmed on Win 10 with non-altered repo

**Comment by kjcartledge** [comment]
Log of a successful submit on Mac: [git-submitter0.txt](https://github.com/thomas4g/git-submitter/files/145404/git-submitter0.txt)

Seems windows does something weird with the encoding...

Windows (failure): 
<img width="696" alt="screen shot 2016-02-24 at 4 05 50 pm" src="https://cloud.githubusercontent.com/assets/6657958/13301008/d9528062-db10-11e5-90e3-c50c3be371a3.png">

Mac (success):
<img width="695" alt="screen shot 2016-02-24 at 4 05 59 pm" src="https://cloud.githubusercontent.com/assets/6657958/13301026/e6d5aa5c-db10-11e5-80c0-6bc6013fce9e.png">
